version: 2.1

orbs:
  android: circleci/android@3.0.2

jobs:
  build:
    docker:
      - image: cimg/android:2023.12
    resource_class: large
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx4g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=true -Dkotlin.incremental=false"
    steps:
      - checkout

      - run:
          name: Setup Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            echo "JAVA_HOME=$JAVA_HOME" >> $BASH_ENV
            java -version

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}-{{ checksum "core/build.gradle.kts" }}

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies
            ./gradlew :app:dependencies
            ./gradlew :core:dependencies

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}-{{ checksum "core/build.gradle.kts" }}

      - run:
          name: Assemble Core Module
          command: ./gradlew :core:assembleRelease
      - run:
          name: Check Core Module
          command: ./gradlew :core:lintRelease
      - run:
          name: Test Core Module
          command: ./gradlew :core:testReleaseUnitTest
      - run:
          name: Build App Module
          command: ./gradlew :app:assembleRelease --stacktrace
      - run:
          name: Test App Module
          command: ./gradlew :app:testReleaseUnitTest
      - run:
          name: Build full project
          command: ./gradlew assembleRelease --stacktrace
      - store_artifacts:
          path: app/build/reports
          destination: app-reports

      - store_artifacts:
          path: core/build/reports
          destination: core-reports

      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release-apk

      - store_test_results:
          path: app/build/test-results

      - store_test_results:
          path: core/build/test-results

      - run:
          name: Copy ProGuard Missing Rules (if exists)
          command: |
            mkdir -p /tmp/proguard-rules/
            if [ -f app/build/outputs/mapping/release/missing_rules.txt ]; then
              cp app/build/outputs/mapping/release/missing_rules.txt /tmp/proguard-rules/
            fi
          when: on_fail

      - store_artifacts:
          path: /tmp/proguard-rules/
          destination: proguard-rules